version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    tty: true
    depends_on:
      - node-app
    networks:
    - node-network
    ports:
    - 8080:80
  node-app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    networks:
      - node-network
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - node-network

networks:
  node-network:
    driver: bridge